blank_issues_enabled: false  # ç¦æ­¢åˆ›å»ºç©ºç™½ Issueï¼Œå¼ºåˆ¶ä½¿ç”¨æ¨¡æ¿
contact_links:
  - name: ğŸ’¬ Telegram Discussion / äº¤æµç¾¤ç»„
    url: https://t.me/qiao_blog # å¦‚æœæœ‰ TG ç¾¤å¯ä»¥å¡«ï¼Œæ²¡æœ‰åˆ™åˆ é™¤æ­¤æ®µ
    about: Please ask general questions here. / é€šç”¨é—²èŠä¸è®¨è®ºè¯·ç§»æ­¥è¿™é‡Œã€‚
  - name: ğŸ“– Metacubex Wiki
    url: https://wiki.metacubex.one/
    about: Official documentation for Clash Meta. / é‡åˆ°é…ç½®å‚æ•°é—®é¢˜ï¼Œè¯·å…ˆæŸ¥é˜…å®˜æ–¹ Wikiã€‚
